export {default as LogoAlta} from './images/logo.png'
export {default as Heroes} from './images/heroes.png'
export {default as Warning} from './images/warning.svg'
export {default as Device} from './images/Device.svg'
export {default as Dashboard} from './images/Dashboard.svg'
export {default as Service} from './images/Service.svg'
export {default as Report} from './images/Report.svg'
export {default as NumLevel} from './images/NumLevel.svg'
export {default as More} from './images/More.svg'
export {default as Setting} from './images/Setting.svg'
export {default as Notify} from './images/notification.svg'
export {default as Avatar} from './images/avatar.svg'

// Article

export {default as Article1} from './images/article-1.svg'
export {default as Article2} from './images/article-2.svg'
export {default as Article3} from './images/article-3.svg'
export {default as Article4} from './images/article-4.svg'
export {default as Up} from './images/up.svg'
export {default as Down} from './images/down.svg'
export {default as DropDown} from './images/fi_chevron-down.svg'
export {default as AddSquare} from './images/add-square.svg'
export {default as SearchIcon} from './images/search.svg'
export {default as EditIcon} from './images/edit-square.svg'
