export {default as LogoAlta} from './images/logo.png'
export {default as Heroes} from './images/heroes.png'
export {default as Warning} from './images/warning.svg'
export {default as Device} from './images/Device.svg'
export {default as Dashboard} from './images/Dashboard.svg'
export {default as Service} from './images/Service.svg'
export {default as Report} from './images/Report.svg'
export {default as NumLevel} from './images/NumLevel.svg'
export {default as More} from './images/More.svg'
export {default as Setting} from './images/Setting.svg'
export {default as Notify} from './images/notification.svg'
export {default as Avatar} from './images/avatar.svg'

// Article

export {default as Article1} from './images/article-1.svg'
export {default as Article2} from './images/article-2.svg'
export {default as Article3} from './images/article-3.svg'
export {default as Article4} from './images/article-4.svg'
export {default as Up} from './images/up.svg'
export {default as Down} from './images/down.svg'
export {default as DropDown} from './images/fi_chevron-down.svg'
export {default as DropUp} from './images/drop-up.svg'
export {default as AddSquare} from './images/add-square.svg'
export {default as SearchIcon} from './images/search.svg'
export {default as EditIcon} from './images/edit-square.svg'
export {default as ChevronLeft} from './images/chevron-left.svg'
export {default as ChevronRight} from './images/chevron-right.svg'
export {default as IconDownload} from './images/download.svg'
export {default as CloseIcon} from './images/fi_x.svg'
export {default as DownloadIcon} from './images/download-icon.svg'
export {default as ArrowIcon} from './images/arrow.svg'
export {default as LogoutIcon} from './images/logout.svg'
export {default as AvatarTest} from './images/avatar-tesst.svg'
export {default as CameraIcon} from './images/camera.svg'
export {default as AngleRightIcon} from './images/angle-right.svg'


export {default as DefaultAvatar} from './images/Avatar.png'
export {default as ImageEmptyResult} from './images/empty.png'

export {default as BackIcon} from './images/back-square.svg'
export {default as NotifyWhite} from './images/notificationWhite.svg'

export {default as DeviceColor} from './images/deviceColor.svg'
export {default as ServiceColor} from './images/serviceColor.svg'
export {default as GiveNumberColor} from './images/giveNumberColor.svg'